import argparse
import os
from ultralytics import YOLO

def fine_tune_yolo_model(data_yaml_path, initial_model_path, output_path):
    """
    Runs the YOLO fine-tuning process.
    """

    # 1. Initialize the Model
    # Load the initial model (yolov8n.pt or your current model)
    print(f"Loading initial model from: {initial_model_path}")
    model = YOLO(initial_model_path)

    # Extract the directory and filename for the final model save path
    output_dir = os.path.dirname(output_path)
    output_name = os.path.splitext(os.path.basename(output_path))[0]

    # 2. Train the Model
    print(f"Starting training with data: {data_yaml_path}")
    print(f"Output will be saved to: {output_dir} with run name: {output_name}")

    results = model.train(
        data=data_yaml_path,
        epochs=250,
        imgsz=640,
        batch=8,
        patience=50,
        optimizer='SGD',
        name=output_name,
        project=output_dir, # This directs the output to your desired location
        exist_ok=True       # Allow the directory to exist
    )

    # YOLOv8 saves the best model in runs/detect/name/weights/best.pt
    # We rename/copy it to the exact path requested by the Java service
    final_model_source = os.path.join(output_dir, output_name, 'weights', 'best.pt')

    if os.path.exists(final_model_source):
        # The Java service expects the model to be at output_path, so we copy it.
        # However, for simplicity and to prevent permission issues,
        # let's modify the Java service to directly use the file generated by YOLO in the 'runs/detect' structure.
        # But for this to work with your request, we need to explicitly save it:

        # Save the best model to the exact path requested by Java
        os.rename(final_model_source, output_path)
        print(f"Training complete. Best model saved to: {output_path}")

        # Clean up the intermediate run directory (optional)
        # shutil.rmtree(os.path.join(output_dir, output_name))

    else:
        raise FileNotFoundError(f"Trained model not found at expected path: {final_model_source}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="YOLO Model Fine-Tuning Script.")
    parser.add_argument('--data_yaml', required=True, help="Path to the data.yaml file.")
    parser.add_argument('--initial_model', required=True, help="Path to the initial .pt model file.")
    parser.add_argument('--output_path', required=True, help="Full path where the final fine-tuned model (.pt) should be saved.")

    args = parser.parse_args()

    try:
        fine_tune_yolo_model(args.data_yaml, args.initial_model, args.output_path)
    except Exception as e:
        print(f"An error occurred during training: {e}", flush=True)
        # Exit with a non-zero code to signal failure to the Java process
        exit(1)